### ISSUE TITLE
recent versions not available on FDroid

### ISSUE THREAD

**Issue by TjrGithub** [n76/Local-GSM-Backend#104] opened 2017-08-05 14:38 UTC
The most recent version available on FDroid is 1.4.14. However, there are several newer versions on GitHub, including a bugfix for #103.

**Comment by n76** [comment] 2017-08-07 00:12
Duplicate of https://github.com/n76/Local-GSM-Backend/issues/102

Closing as duplicate, but if the latest does not show up on F-Droid will re-open.

**Closed by n76** 2017-08-07 00:12 UTC
