### ISSUE TITLE
confirmed-working API key is deemed invalid

### ISSUE THREAD

**Issue by TjrGithub** [n76/Local-GSM-Backend#103] opened 2017-08-02 09:41 UTC
Hi,
I requested an API key from http://opencellid.org/#register. The key works because I can successfully download https://download.unwiredlabs.com/ocid/downloads?token=9...c&file=cell_towers.csv.gz on my computer. However, whenever I copy-paste the API key into the expert preferences, the app complains about an invalid API key and won't let me replace the old API key from before unwiredlabs.
Error message: ("Der API-Schlüssel ist ungültig. Gebe einen gültigen ein (oder deaktiviere die OpenCellID-Option)." Catlog doesn't show anything relevant.

The new API key is a 14-digit lower-case base64 string, maybe some kind of validation is going wrong?

Version: localgmsnlpbackend 1.4.14 from FDroid. Android 6.0.1 Slimrom.

update: manually editing the preferences xml file doesn't work, either.

**Comment by n76** [comment] 2017-08-02 14:09
This is a duplicate of the end of https://github.com/n76/Local-GSM-Backend/issues/96 and was fixed in v1.4.15, see https://github.com/n76/Local-GSM-Backend/commit/993050ec69bd1f9a70b52a61bba763b01e2cefdd

**Closed by n76** 2017-08-02 14:09 UTC
