### ISSUE TITLE
"Error during database update"

### ISSUE THREAD

**Issue by catFreeAndroid** [n76/Local-GSM-Backend#84] opened 2016-10-30 11:34 UTC
Every time I try to update or create the database using the lacells script with a specific country selected, I get the following error:
`java.lang.ArraylndexOutOfBoundsException: length=10; index=-1`

I tried to reset the app cleaning the data in the settings with no avail. It worked fine in the past.

**Comment by n76** [comment] 2016-10-30 23:52
Please confirm the version of Local-GSM-Backend you are having the issue with, the country you are having an issue with and the data source(s) you have selected so I can duplicate the issue.

**Comment by catFreeAndroid** [comment] 2016-10-31 20:27
CM 13.0 (Android 6.0.1)
Local-GSM-Backend version 1.4.7
XposedUnifiedNLP version 1.0
UnifiedNlp version 1.6.7

Country: Portugal
MCC filter: 268
Data source: lacells

**Comment by n76** [comment] 2016-10-31 22:09
Duplicate of https://github.com/n76/Local-GSM-Backend/issues/83 and is fixed in v1.4.9.

Looks like F-Droid has not yet updated their build to the latest tagged release.

**Closed by n76** 2016-10-31 22:09 UTC

**Comment by szilardx** [comment] 2016-11-02 13:07
I do not know how the build process works, but I found this in a log on f-droid.
https://f-droid.org/wiki/page/org.fitchfamily.android.gsmlocation/lastbuild_56

**Comment by n76** [comment] 2016-11-02 13:26
Looks like they don't have the newer version of Gradle in their build environment. That is not something I can do much about. You can compile it your self using Android Studio (and if you don't have Android Studio installed that is pretty easy to do, just follow the instructions from Google).

**Comment by catFreeAndroid** [comment] 2016-11-05 14:40
I just built the latest version available in this repository using Android SDK, then I uninstalled the older version (1.4.7), installed the apk, verified from the settings menu the app version was "1.4.8". Repeated every step described above and had the same error.
