### ISSUE TITLE
Does not respond to location request

### ISSUE THREAD

**Issue by FoxyBee** [n76/Local-GSM-Backend#4] opened 2015-01-12 13:46 UTC
I have the following system: Android 4.4.4 - ART - CyanogenMod 11-20150105-nightly-hammerhead with UnifiedNlp 1.1.3 + LocalGsmNlpBackend 0.5.6 installed from FDroid.

With a clean reboot and location set to battery saving (wifi + mobile network), OsmAnd maps or SatStat unable to get location. Looking in OS Monitor I do not see GSMLocationBackend process running. If I go into UnifiedNlp settings screen and launch the backend (by touching the settings icon), then I am able to get location. However, it appears that the process once again stops responding if I swipe away the UnifiedNlp screen from recents. The GSMLocationBackend process is still listed in the OS Monitor process list, however it just does not respond to location requests.

**Comment by n76** [comment] 2015-01-12 20:48
At present I cannot duplicate your problem. Can you get a logcat for showing information from org.microg.nlp.location.BackendFuser . . . That should show which backends it is calling and what it did with the information.

**Comment by FoxyBee** [comment] 2015-01-13 04:09
Here is the logcat filtered by ".nlp."

BTW, I was experimenting and sometimes it worked without me starting the UnifiedNlp Settings app however it's not consistent. For this log I cleared cache from TWRP & rebooted into system:

01-12 18:23:56.401 I/ActivityManager(608): Start proc com.google.android.gms for service com.google.android.gms/org.microg.nlp.location.LocationServiceV2: pid=1113 uid=10085 gids={50085}
01-12 18:23:56.681 D/org.microg.nlp.geocode.BackendHelper(1113): Binding to: Intent { act=org.microg.nlp.GEOCODER_BACKEND pkg=org.microg.nlp.backend.nominatim cmp=org.microg.nlp.backend.nominatim/.BackendService }
01-12 18:23:56.721 I/ActivityManager(608): Start proc org.microg.nlp.backend.nominatim for service org.microg.nlp.backend.nominatim/.BackendService: pid=1266 uid=10099 gids={50099, 3003, 1028, 1015}
01-12 18:23:56.801 D/ActivityThread(1266): handleBindApplication:org.microg.nlp.backend.nominatim
01-12 18:23:56.891 D/org.microg.nlp.geocode.BackendHelper(1113): Bound to: ComponentInfo{org.microg.nlp.backend.nominatim/org.microg.nlp.backend.nominatim.BackendService}
01-12 18:24:06.887 D/org.microg.nlp.geocode.BackendHelper(1113): Unbinding from: Intent { act=org.microg.nlp.GEOCODER_BACKEND pkg=org.microg.nlp.backend.nominatim cmp=org.microg.nlp.backend.nominatim/.BackendService }
01-12 18:24:06.907 D/org.microg.nlp.geocode.BackendHelper(1113): Binding to: Intent { act=org.microg.nlp.GEOCODER_BACKEND pkg=org.microg.nlp.backend.nominatim cmp=org.microg.nlp.backend.nominatim/.BackendService }
01-12 18:24:06.907 D/org.microg.nlp.geocode.BackendHelper(1113): Bound to: ComponentInfo{org.microg.nlp.backend.nominatim/org.microg.nlp.backend.nominatim.BackendService}
01-12 18:24:06.917 V/org.microg.nlp.location.LocationProviderV2(1113): onSetRequest: ProviderRequest[ON interval=+24h0m0s0ms] by WorkSource{1000 android}
01-12 18:24:06.917 V/org.microg.nlp.location.LocationProviderV2(1113): onSetRequest: request: Request[POWER_LOW network requested=+24h0m0s0ms fastest=+24h0m0s0ms]
01-12 18:24:06.917 V/org.microg.nlp.location.LocationProviderV2(1113): using autoUpdate=true autoTime=86400000
01-12 18:24:06.977 V/org.microg.nlp.location.LocationProviderV2(1113): onSetRequest: ProviderRequest[ON interval=+24h0m0s0ms] by WorkSource{1000 android}
01-12 18:24:06.977 V/org.microg.nlp.location.LocationProviderV2(1113): onSetRequest: request: Request[POWER_LOW network requested=+24h0m0s0ms fastest=+24h0m0s0ms]
01-12 18:24:06.977 V/org.microg.nlp.location.LocationProviderV2(1113): using autoUpdate=true autoTime=86400000
01-12 18:28:06.249 V/org.microg.nlp.location.LocationProviderV2(1113): onSetRequest: ProviderRequest[ON interval=0] by WorkSource{10073 com.vonglasow.michael.satstat}
01-12 18:28:06.249 V/org.microg.nlp.location.LocationProviderV2(1113): onSetRequest: request: Request[POWER_LOW network requested=+24h0m0s0ms fastest=+24h0m0s0ms]
01-12 18:28:06.249 V/org.microg.nlp.location.LocationProviderV2(1113): onSetRequest: request: Request[POWER_LOW network requested=0 fastest=0]
01-12 18:28:06.249 V/org.microg.nlp.location.LocationProviderV2(1113): using autoUpdate=true autoTime=1500
01-12 18:28:15.839 V/org.microg.nlp.location.LocationProviderV2(1113): onSetRequest: ProviderRequest[ON interval=+24h0m0s0ms] by WorkSource{1000 android}
01-12 18:28:15.839 V/org.microg.nlp.location.LocationProviderV2(1113): onSetRequest: request: Request[POWER_LOW network requested=+24h0m0s0ms fastest=+24h0m0s0ms]
01-12 18:28:15.839 V/org.microg.nlp.location.LocationProviderV2(1113): using autoUpdate=true autoTime=86400000
01-12 18:28:29.149 V/org.microg.nlp.location.LocationProviderV2(1113): onSetRequest: ProviderRequest[ON interval=0] by WorkSource{10073 com.vonglasow.michael.satstat}
01-12 18:28:29.149 V/org.microg.nlp.location.LocationProviderV2(1113): onSetRequest: request: Request[POWER_LOW network requested=+24h0m0s0ms fastest=+24h0m0s0ms]
01-12 18:28:29.149 V/org.microg.nlp.location.LocationProviderV2(1113): onSetRequest: request: Request[POWER_LOW network requested=0 fastest=0]
01-12 18:28:29.149 V/org.microg.nlp.location.LocationProviderV2(1113): using autoUpdate=true autoTime=1500
01-12 18:28:38.999 V/org.microg.nlp.location.LocationProviderV2(1113): onSetRequest: ProviderRequest[ON interval=+24h0m0s0ms] by WorkSource{1000 android}
01-12 18:28:38.999 V/org.microg.nlp.location.LocationProviderV2(1113): onSetRequest: request: Request[POWER_LOW network requested=+24h0m0s0ms fastest=+24h0m0s0ms]
01-12 18:28:38.999 V/org.microg.nlp.location.LocationProviderV2(1113): using autoUpdate=true autoTime=86400000
01-12 18:28:59.539 V/org.microg.nlp.location.LocationProviderV2(1113): onSetRequest: ProviderRequest[ON interval=0] by WorkSource{10100 net.osmand}
01-12 18:28:59.539 V/org.microg.nlp.location.LocationProviderV2(1113): onSetRequest: request: Request[POWER_LOW network requested=+24h0m0s0ms fastest=+24h0m0s0ms]
01-12 18:28:59.539 V/org.microg.nlp.location.LocationProviderV2(1113): onSetRequest: request: Request[POWER_LOW network requested=0 fastest=0]
01-12 18:28:59.539 V/org.microg.nlp.location.LocationProviderV2(1113): using autoUpdate=true autoTime=1500
01-12 18:29:20.329 V/org.microg.nlp.location.LocationProviderV2(1113): onSetRequest: ProviderRequest[ON interval=+24h0m0s0ms] by WorkSource{1000 android}
01-12 18:29:20.329 V/org.microg.nlp.location.LocationProviderV2(1113): onSetRequest: request: Request[POWER_LOW network requested=+24h0m0s0ms fastest=+24h0m0s0ms]
01-12 18:29:20.329 V/org.microg.nlp.location.LocationProviderV2(1113): using autoUpdate=true autoTime=86400000
01-12 18:31:16.569 V/org.microg.nlp.location.LocationProviderV2(1113): onSetRequest: ProviderRequest[ON interval=0] by WorkSource{10073 com.vonglasow.michael.satstat}
01-12 18:31:16.569 V/org.microg.nlp.location.LocationProviderV2(1113): onSetRequest: request: Request[POWER_LOW network requested=+24h0m0s0ms fastest=+24h0m0s0ms]
01-12 18:31:16.569 V/org.microg.nlp.location.LocationProviderV2(1113): onSetRequest: request: Request[POWER_LOW network requested=0 fastest=0]
01-12 18:31:16.569 V/org.microg.nlp.location.LocationProviderV2(1113): using autoUpdate=true autoTime=1500
01-12 18:31:38.169 V/org.microg.nlp.location.LocationProviderV2(1113): onSetRequest: ProviderRequest[ON interval=+24h0m0s0ms] by WorkSource{1000 android}
01-12 18:31:38.179 V/org.microg.nlp.location.LocationProviderV2(1113): onSetRequest: request: Request[POWER_LOW network requested=+24h0m0s0ms fastest=+24h0m0s0ms]
01-12 18:31:38.179 V/org.microg.nlp.location.LocationProviderV2(1113): using autoUpdate=true autoTime=86400000
01-12 18:32:02.579 V/org.microg.nlp.location.LocationProviderV2(1113): onSetRequest: ProviderRequest[ON interval=0] by WorkSource{10073 com.vonglasow.michael.satstat}
01-12 18:32:02.579 V/org.microg.nlp.location.LocationProviderV2(1113): onSetRequest: request: Request[POWER_LOW network requested=+24h0m0s0ms fastest=+24h0m0s0ms]
01-12 18:32:02.579 V/org.microg.nlp.location.LocationProviderV2(1113): onSetRequest: request: Request[POWER_LOW network requested=0 fastest=0]
01-12 18:32:02.579 V/org.microg.nlp.location.LocationProviderV2(1113): using autoUpdate=true autoTime=1500
01-12 18:32:12.789 V/org.microg.nlp.location.LocationProviderV2(1113): onSetRequest: ProviderRequest[ON interval=+24h0m0s0ms] by WorkSource{1000 android}
01-12 18:32:12.789 V/org.microg.nlp.location.LocationProviderV2(1113): onSetRequest: request: Request[POWER_LOW network requested=+24h0m0s0ms fastest=+24h0m0s0ms]
01-12 18:32:12.789 V/org.microg.nlp.location.LocationProviderV2(1113): using autoUpdate=true autoTime=86400000

this is where I opened up UnifiedNlp Settings > configure location backends > GSM Location Backend > click settings

01-12 18:32:36.679 D/org.microg.nlp.PackageReceiver(1113): Intent received: Intent { act=android.intent.action.PACKAGE_RESTARTED dat=package:net.osmand flg=0x10 cmp=com.google.android.gms/org.microg.nlp.PackageReceiver (has extras) }
01-12 18:32:36.679 D/org.microg.nlp.PackageReceiver(1113): Reloading location service...
01-12 18:32:36.679 D/org.microg.nlp.PackageReceiver(1113): Reloading geocoding service...
01-12 18:32:36.729 D/org.microg.nlp.location.BackendHelper(1113): Binding to: Intent { act=org.microg.nlp.LOCATION_BACKEND pkg=org.fitchfamily.android.gsmlocation cmp=org.fitchfamily.android.gsmlocation/.GSMService }
01-12 18:32:36.729 D/org.microg.nlp.geocode.BackendHelper(1113): Unbinding from: Intent { act=org.microg.nlp.GEOCODER_BACKEND pkg=org.microg.nlp.backend.nominatim cmp=org.microg.nlp.backend.nominatim/.BackendService }
01-12 18:32:36.749 D/org.microg.nlp.location.BackendHelper(1113): Not (yet) bound.
01-12 18:32:36.749 D/org.microg.nlp.geocode.BackendHelper(1113): Binding to: Intent { act=org.microg.nlp.GEOCODER_BACKEND pkg=org.microg.nlp.backend.nominatim cmp=org.microg.nlp.backend.nominatim/.BackendService }
01-12 18:32:36.759 D/org.microg.nlp.geocode.BackendHelper(1113): Bound to: ComponentInfo{org.microg.nlp.backend.nominatim/org.microg.nlp.backend.nominatim.BackendService}
01-12 18:32:36.819 D/org.microg.nlp.location.BackendHelper(1113): Bound to: ComponentInfo{org.fitchfamily.android.gsmlocation/org.fitchfamily.android.gsmlocation.GSMService}
01-12 18:32:36.869 V/org.microg.nlp.location.BackendFuser(1113): location=Location[network 43.802898,-79.445251 acc=500 et=+9m1s446ms {Bundle[{noGPSLocation=Location[gsm 43.802898,-79.445251 acc=500 et=+9m1s446ms {Bundle[{AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}], AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}]
01-12 18:32:44.339 D/org.microg.nlp.PackageReceiver(1113): Intent received: Intent { act=android.intent.action.PACKAGE_RESTARTED dat=package:com.vonglasow.michael.satstat flg=0x10 cmp=com.google.android.gms/org.microg.nlp.PackageReceiver (has extras) }
01-12 18:32:44.339 D/org.microg.nlp.PackageReceiver(1113): Reloading location service...
01-12 18:32:44.359 D/org.microg.nlp.PackageReceiver(1113): Reloading geocoding service...
01-12 18:32:44.359 D/org.microg.nlp.location.BackendHelper(1113): Unbinding from: Intent { act=org.microg.nlp.LOCATION_BACKEND pkg=org.fitchfamily.android.gsmlocation cmp=org.fitchfamily.android.gsmlocation/.GSMService }
01-12 18:32:44.359 D/org.microg.nlp.geocode.BackendHelper(1113): Unbinding from: Intent { act=org.microg.nlp.GEOCODER_BACKEND pkg=org.microg.nlp.backend.nominatim cmp=org.microg.nlp.backend.nominatim/.BackendService }
01-12 18:32:44.369 D/org.microg.nlp.geocode.BackendHelper(1113): Binding to: Intent { act=org.microg.nlp.GEOCODER_BACKEND pkg=org.microg.nlp.backend.nominatim cmp=org.microg.nlp.backend.nominatim/.BackendService }
01-12 18:32:44.369 D/org.microg.nlp.location.BackendHelper(1113): Binding to: Intent { act=org.microg.nlp.LOCATION_BACKEND pkg=org.fitchfamily.android.gsmlocation cmp=org.fitchfamily.android.gsmlocation/.GSMService }
01-12 18:32:44.369 D/org.microg.nlp.geocode.BackendHelper(1113): Bound to: ComponentInfo{org.microg.nlp.backend.nominatim/org.microg.nlp.backend.nominatim.BackendService}
01-12 18:32:44.369 D/org.microg.nlp.location.BackendHelper(1113): Not (yet) bound.
01-12 18:32:44.379 D/org.microg.nlp.location.BackendHelper(1113): Bound to: ComponentInfo{org.fitchfamily.android.gsmlocation/org.fitchfamily.android.gsmlocation.GSMService}
01-12 18:32:44.399 V/org.microg.nlp.location.BackendFuser(1113): location=Location[network 43.802898,-79.445251 acc=500 et=+9m8s976ms {Bundle[{noGPSLocation=Location[gsm 43.802898,-79.445251 acc=500 et=+9m8s976ms {Bundle[{AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}], AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}]
01-12 18:32:51.219 V/org.microg.nlp.location.LocationProviderV2(1113): onSetRequest: ProviderRequest[ON interval=0] by WorkSource{10073 com.vonglasow.michael.satstat}
01-12 18:32:51.219 V/org.microg.nlp.location.LocationProviderV2(1113): onSetRequest: request: Request[POWER_LOW network requested=+24h0m0s0ms fastest=+24h0m0s0ms]
01-12 18:32:51.219 V/org.microg.nlp.location.LocationProviderV2(1113): onSetRequest: request: Request[POWER_LOW network requested=0 fastest=0]
01-12 18:32:51.219 V/org.microg.nlp.location.LocationProviderV2(1113): using autoUpdate=true autoTime=1500
01-12 18:32:51.229 V/org.microg.nlp.location.BackendFuser(1113): location=Location[network 43.802898,-79.445251 acc=500 et=+9m8s976ms {Bundle[{noGPSLocation=Location[gsm 43.802898,-79.445251 acc=500 et=+9m8s976ms {Bundle[{AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}], AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}]
01-12 18:32:52.729 V/org.microg.nlp.location.BackendFuser(1113): location=Location[network 43.802898,-79.445251 acc=500 et=+9m8s976ms {Bundle[{noGPSLocation=Location[gsm 43.802898,-79.445251 acc=500 et=+9m8s976ms {Bundle[{AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}], AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}]
01-12 18:32:54.229 V/org.microg.nlp.location.BackendFuser(1113): location=Location[network 43.802898,-79.445251 acc=500 et=+9m8s976ms {Bundle[{noGPSLocation=Location[gsm 43.802898,-79.445251 acc=500 et=+9m8s976ms {Bundle[{AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}], AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}]
01-12 18:32:55.729 V/org.microg.nlp.location.BackendFuser(1113): location=Location[network 43.802898,-79.445251 acc=500 et=+9m8s976ms {Bundle[{noGPSLocation=Location[gsm 43.802898,-79.445251 acc=500 et=+9m8s976ms {Bundle[{AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}], AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}]
01-12 18:32:57.229 V/org.microg.nlp.location.BackendFuser(1113): location=Location[network 43.802898,-79.445251 acc=500 et=+9m8s976ms {Bundle[{noGPSLocation=Location[gsm 43.802898,-79.445251 acc=500 et=+9m8s976ms {Bundle[{AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}], AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}]
01-12 18:32:58.729 V/org.microg.nlp.location.BackendFuser(1113): location=Location[network 43.802898,-79.445251 acc=500 et=+9m8s976ms {Bundle[{noGPSLocation=Location[gsm 43.802898,-79.445251 acc=500 et=+9m8s976ms {Bundle[{AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}], AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}]
01-12 18:33:00.229 V/org.microg.nlp.location.BackendFuser(1113): location=Location[network 43.802898,-79.445251 acc=500 et=+9m8s976ms {Bundle[{noGPSLocation=Location[gsm 43.802898,-79.445251 acc=500 et=+9m8s976ms {Bundle[{AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}], AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}]
01-12 18:33:01.729 V/org.microg.nlp.location.BackendFuser(1113): location=Location[network 43.802898,-79.445251 acc=500 et=+9m8s976ms {Bundle[{noGPSLocation=Location[gsm 43.802898,-79.445251 acc=500 et=+9m8s976ms {Bundle[{AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}], AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}]
01-12 18:33:03.229 V/org.microg.nlp.location.BackendFuser(1113): location=Location[network 43.802898,-79.445251 acc=500 et=+9m8s976ms {Bundle[{noGPSLocation=Location[gsm 43.802898,-79.445251 acc=500 et=+9m8s976ms {Bundle[{AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}], AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}]
01-12 18:33:04.729 V/org.microg.nlp.location.BackendFuser(1113): location=Location[network 43.802898,-79.445251 acc=500 et=+9m8s976ms {Bundle[{noGPSLocation=Location[gsm 43.802898,-79.445251 acc=500 et=+9m8s976ms {Bundle[{AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}], AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}]
01-12 18:33:06.229 V/org.microg.nlp.location.BackendFuser(1113): location=Location[network 43.802898,-79.445251 acc=500 et=+9m8s976ms {Bundle[{noGPSLocation=Location[gsm 43.802898,-79.445251 acc=500 et=+9m8s976ms {Bundle[{AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}], AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}]
01-12 18:33:07.729 V/org.microg.nlp.location.BackendFuser(1113): location=Location[network 43.802898,-79.445251 acc=500 et=+9m8s976ms {Bundle[{noGPSLocation=Location[gsm 43.802898,-79.445251 acc=500 et=+9m8s976ms {Bundle[{AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}], AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}]
01-12 18:33:09.229 V/org.microg.nlp.location.BackendFuser(1113): location=Location[network 43.802898,-79.445251 acc=500 et=+9m8s976ms {Bundle[{noGPSLocation=Location[gsm 43.802898,-79.445251 acc=500 et=+9m8s976ms {Bundle[{AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}], AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}]
01-12 18:33:10.729 V/org.microg.nlp.location.BackendFuser(1113): location=Location[network 43.802898,-79.445251 acc=500 et=+9m8s976ms {Bundle[{noGPSLocation=Location[gsm 43.802898,-79.445251 acc=500 et=+9m8s976ms {Bundle[{AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}], AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}]
01-12 18:33:12.239 V/org.microg.nlp.location.BackendFuser(1113): location=Location[network 43.802898,-79.445251 acc=500 et=+9m8s976ms {Bundle[{noGPSLocation=Location[gsm 43.802898,-79.445251 acc=500 et=+9m8s976ms {Bundle[{AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}], AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}]
01-12 18:33:13.729 V/org.microg.nlp.location.BackendFuser(1113): location=Location[network 43.802898,-79.445251 acc=500 et=+9m8s976ms {Bundle[{noGPSLocation=Location[gsm 43.802898,-79.445251 acc=500 et=+9m8s976ms {Bundle[{AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}], AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}]
01-12 18:33:14.069 V/org.microg.nlp.location.LocationProviderV2(1113): onSetRequest: ProviderRequest[ON interval=+24h0m0s0ms] by WorkSource{1000 android}
01-12 18:33:14.069 V/org.microg.nlp.location.LocationProviderV2(1113): onSetRequest: request: Request[POWER_LOW network requested=+24h0m0s0ms fastest=+24h0m0s0ms]
01-12 18:33:14.069 V/org.microg.nlp.location.LocationProviderV2(1113): using autoUpdate=true autoTime=86400000
01-12 18:33:14.069 V/org.microg.nlp.location.BackendFuser(1113): location=Location[network 43.802898,-79.445251 acc=500 et=+9m8s976ms {Bundle[{noGPSLocation=Location[gsm 43.802898,-79.445251 acc=500 et=+9m8s976ms {Bundle[{AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}], AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}]

**Comment by n76** [comment] 2015-01-13 04:48
Hmmm. Your trace shows UnifiedNLP calling org.fitchfamily.android.gsmlocation which implies that things were working when you did the capture.

I wonder if the issue is that sometimes UnifiedNLP just isn't starting or is not continuing to run. I don't see any other backends being used, so I assume that my GSM location backend is the only one you have installed and enabled.

It might be worthwhile to see if you have the same issue with other backends. If so then it might be a generic UnifiedNLP issue rather than an issue specific to this one backend.

**Comment by n76** [comment] 2015-01-13 04:54
Looking at bit more. . . I only see the "Binding to" log for the location backend after you opened the settings menu. The geocoder backend has that both on start up and after you went into the settings. It looks like UnifiedNLP did not have knowledge of the GSM backend until that time.

If you had previously configured the GSM backend before rebooting, then I think it might be a generic problem with UnifiedNLP. I don't reboot my phone that often, and I do open the settings periodically in order to create a new database so I could well have missed an issue with UnifiedNLP like that.

**Comment by FoxyBee** [comment] 2015-01-13 15:22
Thank you so much for looking into this and I think you may be correct. I have tested again with another backend (GSMLocationNlpBackend 0.0.1.4) and get the same result. I have opened the following new issue: https://github.com/microg/android_packages_apps_UnifiedNlp/issues/22

**Comment by n76** [comment] 2015-01-13 16:03
Assuming it is a UnifiedNlp issue, so closing this report.

**Closed by n76** 2015-01-13 16:03 UTC

**Comment by jensMF** [comment] 2015-02-03 13:10
I have the same problem with omnirom-android 4.4.4 on gt-i9100 (Samsung galaxy s2) but in osmonitor the process is running, but i can't get location. I tried it with unifiednlp 1.2.2 from F-Droid as normal installation and as system-app. And i tried it with all buildflavors as normal app and as system app. I used the localgsmnlpbackend 0.5.6 from f-droid and I tried a self-build version of it (0.5.6 as well) …

**Comment by jensMF** [comment] 2015-02-03 14:43
Ok, something different must be the problem. In thee logcat it schows the location it gets… but öffis and oandbackup don't get the location info…

**Comment by jensMF** [comment] 2015-02-03 14:59
Ok, something different must be the problem. In thee logcat it schows the location it gets… but öffis and oandbackup don't get the location info…

**Comment by jensMF** [comment] 2015-02-12 21:20
Ok, now I have localgsmnlpbackend 0.5.8 and i don't get a location with it. I don't know why…
Here is the logcat: http://hastebin.com/jolaludopo.coffee

**Comment by takiainen** [comment] 2015-08-11 06:27
I cannot get location with localgsmnlpbackend either. My phone is Oneplus one and i've tried different Lollipop based roms (Exodus,AICP,Blisspop,SlimLP) without success. Stock settings, no GAPPS.

Privacy guard show that localgsmnlpbackend has asked location several hundred times (and always allowed), but I localgsmnlpbackend never show up on "settings --> location: recent location requests" -list. 

Wifi Backend however shows up on that list and also gives me location with Osmand or SatSat.

Where's the problem?

**Comment by n76** [comment] 2015-08-11 14:46
Response to takiainen at https://github.com/n76/Local-GSM-Backend/issues/30
